### ISSUE TITLE
Fix "to be" conjugation

### ISSUE THREAD

**Issue by jakub-c** [slowernews/notebook#1]
https://github.com/galfarragem/learning-notes/blob/3e42fd97f785e4a9383c90c5288935354b8bcc17/notes-polish%20language.yaml#L9

the right conjugation is: `jestem..byłem`

`jestem..biłem` literally means `I am...I beat (simple past tense)`

**Comment by slowernews** [comment]
Thanks. My level on Polish language is still weak..

All files on that repo are WIP but I leave them public as they can still be useful to somebody.
